# ???????????????????????????????????????????????????????????????
# CAMPAIGN SERVICE ? Gestion des campagnes, contacts, templates
# ???????????????????????????????????????????????????????????????

server.port=8081
spring.application.name=campaign-service

# ??? PostgreSQL ???
spring.datasource.url=jdbc:postgresql://localhost:5432/campaign_db
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000

# ??? JPA ???
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_batch_fetch_size=20
spring.jpa.open-in-view=false



# ??? Eureka ???
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.value}

# ??? Config campagne ???
campaign.scheduler.enabled=true
campaign.scheduler.poll-interval-ms=30000
campaign.sending.batch-size=50
campaign.sending.delay-between-batch-ms=1000
campaign.defaults.from-name=PFE Mailer
campaign.defaults.from-email=noreply@khaoulaboudriga.me
campaign.defaults.reply-to=noreply@khaoulaboudriga.me

# ??? Feign Client ???
feign.client.config.smtp-service.connect-timeout=5000
feign.client.config.smtp-service.read-timeout=30000
feign.client.config.smtp-service.logger-level=BASIC

# ??? Actuator ???
management.endpoints.web.exposure.include=health,info,metrics,prometheus

# ??? Logging ???
logging.level.com.pfe.campaign=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=WARN

# ??? Swagger / OpenAPI ???
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.info.title=Campaign Service API
springdoc.info.description=API de gestion des campagnes, contacts et templates
springdoc.info.version=1.0.0z

# JWT (même secret que auth-service)
jwt.secret=ThisIsAVeryLongAndSecureJWTSigningKeyForFreeProMailer2026DontShareItEver!!

# Upload pièces jointes
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB
attachment.upload.dir=./uploads/attachments