# ??? REPORTING SERVICE ???
server.port=8085
spring.application.name=reporting-service

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/reporting_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=15

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Export
reporting.export.pdf.template-path=classpath:templates/reports/
reporting.export.excel.max-rows=100000
reporting.cache.enabled=true
reporting.cache.ttl-minutes=15
reporting.kpi.refresh-cron=0 */5 * * * ?

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.value}

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.metrics.tags.application=reporting-service

# Logging
logging.level.com.pfe.reporting=DEBUG