# ???????????????????????????????????????????
#  SMTP SERVICE ? Configuration
# ????????????????????????????????????????????

spring.application.name=smtp-service
server.port=8082

# ??? Base de données ???
spring.datasource.url=jdbc:postgresql://localhost:5432/smtp_db
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ??? Eureka ???
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# ??? SMTP Hostname ???
smtp.hostname=khaoulaboudriga.me

# ??? Relay vers MailHog (GRATUIT + ILLIMITÉ) ???
smtp.relay.enabled=true
smtp.relay.host=localhost
smtp.relay.port=1025
smtp.relay.username=
smtp.relay.password=
smtp.relay.starttls=false

# ??? Timeouts ???
smtp.sending.timeout-ms=15000
smtp.sending.connection-timeout-ms=10000

# ??? Queue ???
smtp.dequeue.batch-size=10

# ??? Fair Scheduler ???
smtp.scheduler.max-per-second=12
smtp.scheduler.daily-limit=50000
smtp.dequeue.poll-interval-ms=1000
smtp.dequeue.lock-timeout-minutes=5
# ??? DKIM ???
dkim.enabled=true
dkim.domain=khaoulaboudriga.me
dkim.selector=mail
dkim.private-key-path=classpath:dkim/private.key

# ??? Actuator ???
management.endpoints.web.exposure.include=health,info,metrics

